[package]
name = "svm-circuits"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ark-ed25519 = "0.4.0"
halo2-base = "0.4.1"
halo2-ecc = "0.4.0"
halo2_proofs = "0.3.0"
num-bigint = "0.4.4"
